# # This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
# version: 2.1

# orbs:
#   node: circleci/node@4.1
    # aws-code-deploy: circleci/aws-code-deploy@0.0.11

# workflows:
#   sample:
#     jobs:
#       - node/test:
#           version: '15.1'
#           # This is the node version to use for the `cimg/node` tag
#           # Relevant tags can be found on the CircleCI Developer Hub
#           # https://circleci.com/developer/images/image/cimg/node

version: 2.1

jobs:
  build:
    docker:
      - image: cibuilds/snapcraft:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
      - persist_to_workspace:
          root: .
          paths: 
            - .
  test:
    machine: 
      image: cibuilds/snapcraft:stable
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
        image: cibuilds/snapcraft:stable
    steps:
    - attach_workspace:
        at: .
    - checkout
    - run: aws s3 snyc /msg-app arn:aws:s3:::myawsmessagebucket


workflows:
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test